#!/bin/bash
# Generates cryort_stubs.ll — abort-stubs for stdlib symbols cryoc references
# but can't yet emit definitions for (generic specializations + non-generic
# stdlib methods absent from the C++-bootstrapped libcryo.a).  Each stub
# prints a fatal message and aborts.
#
# Drop this once stdlib is rebuilt with cryoc.

set -e
BUILD_LOG=${1:-/tmp/build.log}
OUT=${2:-/home/phock/Programming/apps/CryoLang/cryoc/runtime/cryort_stubs.ll}

UNDEF_FILE=$(mktemp)
trap "rm -f $UNDEF_FILE" EXIT

grep "undefined reference" "$BUILD_LOG" \
  | grep -F 'C$' \
  | awk -F'`' '{print $2}' \
  | tr -d "'" \
  | sort -u > "$UNDEF_FILE"

count=$(wc -l < "$UNDEF_FILE")

{
  echo '; cryort_stubs.ll — auto-generated by gen_stubs.sh.'
  echo '; Defines abort-stubs for stdlib symbols that v0.2 cryoc references but'
  echo '; the old-mangled libcryo.a does not provide.  Each stub prints a fatal'
  echo '; message and aborts.  Regenerate after each link attempt while'
  echo '; bootstrapping; remove entirely once stdlib rebuilds with cryoc.'
  echo ''
  echo 'target triple = "x86_64-pc-linux-gnu"'
  echo ''
  echo 'declare void @abort() noreturn'
  echo 'declare i32 @puts(ptr)'
  echo ''
  echo '@.cryort_stub_msg = private unnamed_addr constant [50 x i8] c"FATAL: cryort stub hit (stdlib symbol unresolved)\00"'
  echo ''
  while IFS= read -r sym; do
    [ -z "$sym" ] && continue
    echo "define void @\"$sym\"() noreturn {"
    echo "  %1 = call i32 @puts(ptr @.cryort_stub_msg)"
    echo "  call void @abort()"
    echo "  unreachable"
    echo "}"
  done < "$UNDEF_FILE"
} > "$OUT"

echo "Wrote $count stubs to $OUT"
