#*******************************************************************************
#  Copyright 2025 Jacob LeQuire                                                *
#  SPDX-License-Identifier: Apache-2.0                                         *
#    Licensed under the Apache License, Version 2.0 (the "License");           *
#    you may not use this file except in compliance with the License.          *
#    You may obtain a copy of the License at                                   *
#                                                                              *
#    http://www.apache.org/licenses/LICENSE-2.0                                *
#                                                                              *
#    Unless required by applicable law or agreed to in writing, software       *
#    distributed under the License is distributed on an "AS IS" BASIS,         *
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
#    See the License for the specific language governing permissions and       *
#    limitations under the License.                                            *
#                                                                              *
#*******************************************************************************

#*******************************************************************************
# Shared Makefile Configuration                                                *
# This file contains common settings used by main makefile and tool makefiles *
#*******************************************************************************

# Optimization and debug settings
OPTIMIZATION =  -Og
NO_WARNINGS =   -w
DEBUG_FLAGS =   -D_CRT_SECURE_NO_WARNINGS  $(NO_WARNINGS) -g
C_STANDARD =    -std=c23
CXX_STANDARD =  -std=c++23

# Determine number of CPU cores
ifeq ($(OS), Windows_NT)
    NUM_CORES = $(NUMBER_OF_PROCESSORS)
else
    NUM_CORES = $(shell nproc)
endif

NUM_JOBS = $(shell expr $(NUM_CORES) + 1)

# OS-specific settings for compilers
ifeq ($(OS), Windows_NT)
# Windows settings
	C_COMPILER = clang
	CXX_COMPILER = clang++
	PYTHON = python
else
# Linux settings
	C_COMPILER = clang-20
	CXX_COMPILER = clang++-20
	PYTHON = python3
endif

# Include paths
LINUX_INCLUDES =    -I./include -I/usr/lib/llvm-20/include
WIN_INCLUDES =      -I"C:/msys64/mingw64/include" -I./include

# OS-specific settings
ifeq ($(OS), Windows_NT)
    # Windows settings
    CC =            $(C_COMPILER) $(C_STANDARD) $(DEBUG_FLAGS) $(OPTIMIZATION)
    CXX =           $(CXX_COMPILER) $(CXX_STANDARD) $(DEBUG_FLAGS) $(OPTIMIZATION)
    CFLAGS =        $(WIN_INCLUDES) $(LLVM_CFLAGS) -fexceptions
    CXXFLAGS =      $(WIN_INCLUDES) $(LLVM_CXXFLAGS) -fexceptions
    LDFLAGS =       $(LLVM_LDFLAGS) $(STDLIBS) -v
    LLVM_CONFIG =   C:/msys64/mingw64/bin/llvm-config.exe
    LLVM_CFLAGS =   $(shell $(LLVM_CONFIG) --cflags)
    LLVM_CXXFLAGS = $(shell $(LLVM_CONFIG) --cxxflags)
    # Use full path to library instead of -l flag for Windows compatibility
    LLVM_LDFLAGS =  $(shell $(LLVM_CONFIG) --ldflags) C:/msys64/mingw64/lib/libLLVM-20.dll.a
    STDLIBS :=      
    MKDIR =         mkdir
    RMDIR =         rmdir /S /Q
    DEL =           del /Q
    BIN_SUFFIX =    .exe
else
    # Linux settings
    CC =            $(C_COMPILER) $(C_STANDARD) $(DEBUG_FLAGS) $(OPTIMIZATION)
    CXX =           $(CXX_COMPILER) $(CXX_STANDARD) $(DEBUG_FLAGS) $(OPTIMIZATION)
    CFLAGS =        $(LINUX_INCLUDES) $(LLVM_CFLAGS) -fexceptions
    CXXFLAGS =      $(LINUX_INCLUDES) $(LLVM_CXXFLAGS) -fexceptions
    LLVM_CONFIG =   llvm-config-20
    LLVM_CFLAGS =   $(shell $(LLVM_CONFIG) --cflags)
    LLVM_CXXFLAGS = $(shell $(LLVM_CONFIG) --cxxflags)
    LLVM_LDFLAGS =  $(shell $(LLVM_CONFIG) --ldflags) $(shell $(LLVM_CONFIG) --libs) $(shell $(LLVM_CONFIG) --system-libs)
    LDFLAGS =       $(LLVM_LDFLAGS) -lpthread -v
    MKDIR =         mkdir -p
    RMDIR =         rm -rf
    DEL =           rm -f
    BIN_SUFFIX =    
endif
