/**
 * CryoLang WebAssembly TypeScript API
 * 
 * High-level TypeScript wrapper for the CryoLang WebAssembly compiler.
 * This provides a clean, promise-based API for web applications.
 */

export interface CryoCompileResult {
  success: boolean;
  errors: string[];
  warnings: string[];
  ast?: string;
  wasmBytes?: Uint8Array;
}

export interface CryoError {
  message: string;
  line: number;
  column: number;
  severity: 'error' | 'warning' | 'info';
}

export interface CryoCompilerOptions {
  target?: 'wasm32' | 'wasm64' | 'native';
  optimizationLevel?: 0 | 1 | 2 | 3;
  debugInfo?: boolean;
  exportedFunctions?: string[];
  enableJSInterop?: boolean;
}

export interface CryoPlaygroundFeatures {
  formatCode?: boolean;
  autoComplete?: boolean;
  syntaxHighlighting?: boolean;
  errorHighlighting?: boolean;
}

export class CryoCompiler {
  private module: any = null;
  private initialized = false;

  /**
   * Initialize the CryoLang WebAssembly compiler
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      return;
    }

    try {
      // Load the CryoLang WASM module
      // This would be generated by Emscripten
      const CryoModule = await import('./cryo-compiler.js');
      this.module = await CryoModule.default();
      
      // Initialize the WASM runtime
      const initResult = this.module.ccall('cryo_wasm_initialize', 'number', ['number'], [16777216]);
      if (initResult !== 1) {
        throw new Error('Failed to initialize CryoLang WASM runtime');
      }

      this.initialized = true;
    } catch (error) {
      throw new Error(`Failed to initialize CryoLang compiler: ${error}`);
    }
  }

  /**
   * Compile CryoLang source code
   */
  async compile(source: string, options: CryoCompilerOptions = {}): Promise<CryoCompileResult> {
    if (!this.initialized) {
      await this.initialize();
    }

    try {
      // Set compiler options
      if (options.optimizationLevel !== undefined) {
        this.module.ccall('cryo_set_optimization_level', null, ['number'], [options.optimizationLevel]);
      }
      
      if (options.debugInfo !== undefined) {
        this.module.ccall('cryo_enable_debug_info', null, ['number'], [options.debugInfo ? 1 : 0]);
      }

      if (options.target) {
        const targetTriple = this.getTargetTriple(options.target);
        this.module.ccall('cryo_set_target_triple', null, ['string'], [targetTriple]);
      }

      // Compile the source code
      const compileResult = this.module.ccall('cryo_compile_source', 'number', ['string'], [source]);
      
      const result: CryoCompileResult = {
        success: compileResult === 1,
        errors: [],
        warnings: []
      };

      // Get compilation errors
      const errorCount = this.module.ccall('cryo_get_error_count', 'number', [], []);
      for (let i = 0; i < errorCount; i++) {
        const errorMsg = this.module.ccall('cryo_get_error_message', 'string', ['number'], [i]);
        if (errorMsg) {
          result.errors.push(errorMsg);
        }
      }

      // Get AST if successful
      if (result.success) {
        const ast = this.module.ccall('cryo_get_ast', 'string', ['string'], [source]);
        if (ast) {
          result.ast = ast;
        }
      }

      return result;
    } catch (error) {
      return {
        success: false,
        errors: [`Compilation error: ${error}`],
        warnings: []
      };
    }
  }

  /**
   * Validate syntax without full compilation
   */
  async validateSyntax(source: string): Promise<CryoError[]> {
    if (!this.initialized) {
      await this.initialize();
    }

    try {
      const isValid = this.module.ccall('cryo_validate_syntax', 'number', ['string'], [source]);
      
      const errors: CryoError[] = [];
      
      if (!isValid) {
        const errorCount = this.module.ccall('cryo_get_error_count', 'number', [], []);
        for (let i = 0; i < errorCount; i++) {
          const errorMsg = this.module.ccall('cryo_get_error_message', 'string', ['number'], [i]);
          if (errorMsg) {
            errors.push({
              message: errorMsg,
              line: 1, // TODO: Extract from error message
              column: 1, // TODO: Extract from error message  
              severity: 'error'
            });
          }
        }
      }

      return errors;
    } catch (error) {
      return [{
        message: `Syntax validation error: ${error}`,
        line: 1,
        column: 1,
        severity: 'error'
      }];
    }
  }

  /**
   * Format CryoLang source code
   */
  async formatCode(source: string): Promise<string> {
    if (!this.initialized) {
      await this.initialize();
    }

    try {
      // Allocate buffer for formatted code
      const bufferSize = source.length * 2; // Generous buffer
      const buffer = this.module._malloc(bufferSize);
      
      const resultLength = this.module.ccall('cryo_format_source', 'number', 
        ['string', 'number', 'number'], [source, buffer, bufferSize]);
      
      if (resultLength > 0) {
        const formattedCode = this.module.UTF8ToString(buffer, resultLength);
        this.module._free(buffer);
        return formattedCode;
      } else {
        this.module._free(buffer);
        return source; // Return original if formatting failed
      }
    } catch (error) {
      console.error('Code formatting failed:', error);
      return source;
    }
  }

  /**
   * Get autocomplete suggestions
   */
  async getCompletionSuggestions(source: string, cursorPosition: number): Promise<string[]> {
    if (!this.initialized) {
      await this.initialize();
    }

    try {
      const bufferSize = 1024;
      const buffer = this.module._malloc(bufferSize);
      
      const resultLength = this.module.ccall('cryo_get_completion_suggestions', 'number',
        ['string', 'number', 'number', 'number'], 
        [source, cursorPosition, buffer, bufferSize]);
      
      if (resultLength > 0) {
        const suggestionsStr = this.module.UTF8ToString(buffer, resultLength);
        this.module._free(buffer);
        return suggestionsStr.split(',').filter(s => s.trim().length > 0);
      } else {
        this.module._free(buffer);
        return [];
      }
    } catch (error) {
      console.error('Autocomplete failed:', error);
      return [];
    }
  }

  /**
   * Compile to WebAssembly binary
   */
  async compileToWasm(source: string, options: CryoCompilerOptions = {}): Promise<Uint8Array | null> {
    if (!this.initialized) {
      await this.initialize();
    }

    try {
      // Set WASM-specific options
      const target = options.target || 'wasm32';
      const targetTriple = this.getTargetTriple(target);
      this.module.ccall('cryo_set_target_triple', null, ['string'], [targetTriple]);

      // Compile to WASM (this would need additional implementation)
      const outputPath = '/tmp/output.wasm'; // Virtual filesystem path
      const compileResult = this.module.ccall('cryo_compile_to_wasm', 'number', 
        ['string', 'string'], [source, outputPath]);

      if (compileResult === 1) {
        // Read the generated WASM file (would need virtual filesystem support)
        // This is a placeholder - you'd need to implement file system access
        const wasmBytes = new Uint8Array(0); // Placeholder
        return wasmBytes;
      }

      return null;
    } catch (error) {
      console.error('WASM compilation failed:', error);
      return null;
    }
  }

  /**
   * Get compiler version and info
   */
  getVersion(): string {
    if (!this.initialized) {
      return 'Not initialized';
    }

    return this.module.ccall('cryo_get_version', 'string', [], []);
  }

  /**
   * Get supported compilation targets
   */
  getSupportedTargets(): string[] {
    if (!this.initialized) {
      return [];
    }

    const targets = this.module.ccall('cryo_get_supported_targets', 'string', [], []);
    return targets ? targets.split(',') : [];
  }

  /**
   * Clean up resources
   */
  destroy(): void {
    if (this.initialized && this.module) {
      this.module.ccall('cryo_cleanup', null, [], []);
      this.module.ccall('cryo_wasm_shutdown', null, [], []);
      this.initialized = false;
    }
  }

  private getTargetTriple(target: string): string {
    switch (target) {
      case 'wasm32':
        return 'wasm32-unknown-emscripten';
      case 'wasm64':
        return 'wasm64-unknown-emscripten';
      case 'native':
        return 'native';
      default:
        return 'wasm32-unknown-emscripten';
    }
  }
}

// Export default instance for convenience
export const cryoCompiler = new CryoCompiler();

// Example usage function
export async function createCryoPlayground(containerId: string, features: CryoPlaygroundFeatures = {}) {
  const container = document.getElementById(containerId);
  if (!container) {
    throw new Error(`Container element '${containerId}' not found`);
  }

  // Initialize compiler
  const compiler = new CryoCompiler();
  await compiler.initialize();

  // Create basic playground UI
  container.innerHTML = `
    <div style="display: flex; height: 500px; border: 1px solid #ccc;">
      <div style="flex: 1; display: flex; flex-direction: column;">
        <div style="padding: 8px; background: #f5f5f5; border-bottom: 1px solid #ccc;">
          <button id="compile-btn">Compile</button>
          <button id="format-btn">Format</button>
          <select id="target-select">
            <option value="wasm32">WASM32</option>
            <option value="wasm64">WASM64</option>
            <option value="native">Native</option>
          </select>
        </div>
        <textarea id="code-editor" style="flex: 1; font-family: monospace; padding: 8px; border: none; resize: none;" 
                  placeholder="Enter your CryoLang code here...">function main() -> int {
    const message: string = "Hello from CryoLang!";
    return 0;
}</textarea>
      </div>
      <div style="flex: 1; display: flex; flex-direction: column; border-left: 1px solid #ccc;">
        <div style="padding: 8px; background: #f5f5f5; border-bottom: 1px solid #ccc;">
          <strong>Output</strong>
        </div>
        <div id="output-panel" style="flex: 1; padding: 8px; font-family: monospace; background: #fafafa; overflow-y: auto;"></div>
      </div>
    </div>
  `;

  // Add event handlers
  const compileBtn = container.querySelector('#compile-btn') as HTMLButtonElement;
  const formatBtn = container.querySelector('#format-btn') as HTMLButtonElement;
  const codeEditor = container.querySelector('#code-editor') as HTMLTextAreaElement;
  const outputPanel = container.querySelector('#output-panel') as HTMLDivElement;
  const targetSelect = container.querySelector('#target-select') as HTMLSelectElement;

  compileBtn.addEventListener('click', async () => {
    const source = codeEditor.value;
    const target = targetSelect.value as 'wasm32' | 'wasm64' | 'native';
    
    outputPanel.textContent = 'Compiling...';
    
    try {
      const result = await compiler.compile(source, { target });
      
      if (result.success) {
        outputPanel.innerHTML = `<span style="color: green;">✓ Compilation successful!</span>`;
        if (result.ast) {
          outputPanel.innerHTML += `\n\n<details><summary>AST</summary><pre>${result.ast}</pre></details>`;
        }
      } else {
        outputPanel.innerHTML = `<span style="color: red;">✗ Compilation failed:</span>\n${result.errors.join('\n')}`;
      }
    } catch (error) {
      outputPanel.innerHTML = `<span style="color: red;">Error: ${error}</span>`;
    }
  });

  formatBtn.addEventListener('click', async () => {
    const source = codeEditor.value;
    try {
      const formatted = await compiler.formatCode(source);
      codeEditor.value = formatted;
    } catch (error) {
      console.error('Formatting failed:', error);
    }
  });

  return compiler;
}