#!/usr/bin/env python3
"""Rewrite residue.md's description of how the population is made and
checked for the facts reader, and drop its elsewhere section."""
import io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
PATH = os.path.join(ROOT, "scripts", "ns-migration", "residue.md")

POPULATION = """* **The population is read from the compiler, not from the source.**
  `residue.py` reads the records `cryo build --emit=facts` writes for the
  compiler (`make facts`, `.facts/compiler.facts`, refused when missing or
  stale): every call sema resolved that passes a key (`SymbolStr`, `string`,
  `ModulePath`) and every `==` / `!=` comparing keys, each with the callee's
  identity and where each value came from. Which types HOLD declarations is
  placement, over declarations, and stays with `scripts/lane-gate.py`: the
  stores rule 1 places and the array owners rule 1b places as *a member
  table inside its owner*. A METHOD site is a call to a holder's `&this` or
  static method with a key argument, outside the holder's own file and the
  files its store owns; its key is its key arguments' provenance. **The same
  read written INLINE is a site too**: a comparison whose operand is a key
  read off an element of an array the gate places as a TABLE, where the
  innermost loop around the comparison reads that element - directly, through
  a local declared at that loop's depth, or indexed by its counter; an
  element bound outside the innermost loop is the key being searched for,
  not the array being searched. Its read is spelled `Owner::field[]` (a local
  or parameter array `local::Elem[]`, by its element type) and its key is the
  other operand's provenance. A call into a holder that sema left unpinned
  refuses the run. `python scripts/ns-migration/residue.py --count` is the
  size; without a flag it prints every site as `file`, `line`, holder,
  method, key provenance.
"""

CHECK = """* **The check.** `python scripts/ns-migration/residue.py --check` matches
  the table to the tree by (file, method, key provenance) - a line shift is
  not drift, a site added, removed or re-keyed is - and re-derives every
  row's class from `residue_classify.py`, refusing a row whose letter is not
  the classifier's (flipped, blanked, or a letter the classes do not
  include); on OK it prints the count per class from the classifier, so the
  number §0 pins is checked against the tree, the list and the code that
  decides it. A check that read the letters as written let a J row flipped
  to N by hand pass with J one lower. `residue_selftest.py` (`make
  residue-selftest`, in `check-fast` and CI) drives each refusal through a
  throwaway facts file and list. §0's D32 row carries the command and the
  counts.
"""


def cut(text, start, end):
    b = text.index(start)
    e = text.index(end, b)
    return text[:b], text[e:]


def main():
    s = io.open(PATH, encoding="utf-8").read()
    head, rest = cut(s, "* **The population is derived, not recalled.**", "* **The classes are judgement")
    s = head + POPULATION + rest
    head, rest = cut(s, "* **The check.**", "* The table is regenerated by")
    s = head + CHECK + rest
    b = s.index("## Elsewhere: population names on types that hold nothing")
    e = s.index("<!-- residue-elsewhere:end -->") + len("<!-- residue-elsewhere:end -->")
    s = s[:b].rstrip("\n") + "\n" + s[e:].lstrip("\n")
    io.open(PATH, "w", encoding="utf-8", newline="\n").write(s)
    print("residue_prose: ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
