#!/usr/bin/env python3
"""End-to-end gate on the constants `cryo vendor` carries out of a C header.

WHY THIS EXISTS
---------------
The vendor path has two halves that must agree on an AST shape: the importer
BINDS a constant (into a VarDeclNode) and the serializer WRITES it (as `.cryo`
source text).  When they disagree, the importer's own translation report still
says the constant bound, the generator still exits 0, and the constant is
simply absent from the generated file.  Nothing downstream can tell that apart
from a header that never had the constant: the use site fails with `cannot find
value`, one build later, with no pointer back to generation.

That failure shipped.  A cast wrapper added around integer initializers on the
importer side left the serializer's literal-only check rejecting every INTEGER
constant - macro constants, folded probe constants, char constants, and the
`static const` wide-flag shape - while floats, strings and enums kept working,
so the loss looked selective rather than systemic.

WHAT IS ASSERTED
----------------
The gate registers the fixture library under a THROWAWAY `$CRYO_HOME`, then
builds and runs a consumer that reads every constant in it:

  * a constant the serializer drops fails to COMPILE (`cannot find value`),
    which is the real symptom, not a proxy for it;
  * a constant that survives with the wrong value fails the value comparison;
  * `[skip] const` anywhere in the translation report fails the gate even if
    the build succeeds, because the serializer is not entitled to drop a
    constant the importer bound.

Every constant shape a C API uses to publish a value is covered, one per way
the importer can reach one: plain literal, function-like-macro invocation
(folded by the probe TU), constant arithmetic, negative, unsigned hex, char,
float, string, and `static const` wider than an enum.

VALUES ARE PINNED, TYPES ARE NOT.  The consumer casts each integer to i64
before printing, so the gate fails on a dropped or wrong-valued constant but
not on the importer choosing i32 where u32 would also be defensible.  Which
Cryo type a given C constant maps to is a separate question with its own
answer; pinning it here would make this gate fail for reasons that have nothing
to do with what it is watching.

HERMETIC
--------
`$CRYO_HOME` is redirected to a temporary directory, so the vendor registry
this gate writes is thrown away and the developer's real registered libraries
are never read, rewritten, or clobbered.  Nothing is left registered on the
machine after a run.

USAGE
    python3 scripts/vendor-consts-gate.py <path-to-cryo>
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(REPO, "tests", "helpers", "vendor_consts")
STDLIB = os.path.join(REPO, "stdlib")

# name -> (cryo expression suffix, printf spec, expected printed text).
# The expected text is what the C header says the value is, computed here by
# hand so a wrong fold is caught rather than mirrored.
INT_CONSTS = [
    ("VC_PLAIN_INT", "4097"),           # a single literal
    ("VC_TWO_STEP", "259"),             # VC_MAKE_VERSION(1, 3) -> (1 << 8) | 3
    ("VC_ARITH", "4100"),               # VC_PLAIN_INT + 3
    ("VC_NEGATIVE", "-4098"),           # carried as two's-complement, cast back
    ("VC_HEX_U", "8196"),               # 0x00002004u
    ("VC_CHAR", "81"),                  # 'Q'
    ("VC_WIDE_FLAG", "4294967296"),     # static const unsigned long long
]
FLOAT_CONST = ("VC_FLOAT", "3.500")
STRING_CONST = ("VC_STRING", "vendor-consts")

# The controls: shapes that reach the generated file by a path OTHER than
# `render_const`, checked as text because an enum variant is reached through
# its enum rather than as a bare name.  Without them a total failure to
# generate anything would satisfy every assertion above by dropping the
# constants AND the code that reads them.
GENERATED_MUST_CONTAIN = [
    "type enum VcKind",
    "VC_KIND_SOME = 7;",
    "function vc_touch(",
]


def die(msg, *details):
    print("vendor-consts gate: FAIL - %s" % msg, file=sys.stderr)
    for d in details:
        if d:
            print(d.rstrip(), file=sys.stderr)
    sys.exit(1)


def consumer_source():
    lines = [
        "///! Generated by scripts/vendor-consts-gate.py.  Reads every constant",
        "///! the fixture header publishes; a constant the serializer dropped",
        "///! fails to resolve here, which is the symptom the gate watches for.",
        "namespace VendorConstsGate::Main;",
        "",
        "import std::fmt;",
        "import vendor::VendorConsts;",
        "",
        "function main() -> i32 {",
    ]
    for name, _ in INT_CONSTS:
        lines.append('    fmt::printf("%s=%%lld\\n", VendorConsts::%s as i64);'
                     % (name, name))
    lines.append('    fmt::printf("%s=%%.3f\\n", VendorConsts::%s as f64);'
                 % (FLOAT_CONST[0], FLOAT_CONST[0]))
    lines.append('    fmt::printf("%s=%%s\\n", VendorConsts::%s);'
                 % (STRING_CONST[0], STRING_CONST[0]))
    lines += ["    return 0;", "}", ""]
    return "\n".join(lines)


CRYOCONFIG = """[project]
project_name = "vendor_consts_gate"
output_dir   = "build"
target_type  = "executable"
source_dir   = "src"
entry_point  = "src/main.cryo"

[compiler]

[dependencies]
"""


def main():
    if len(sys.argv) < 2:
        die("usage: vendor-consts-gate.py <path-to-cryo>")
    cryo = os.path.abspath(sys.argv[1])
    if not os.path.exists(cryo):
        die("compiler not found at %s (run `make cryo` first)" % cryo)
    if not os.path.isdir(FIXTURE):
        die("fixture missing at %s" % FIXTURE)

    tmp = tempfile.mkdtemp(prefix="cryo-vendor-consts-")
    try:
        env = dict(os.environ)
        # Hermetic: the registry and binding cache both hang off $CRYO_HOME/cache,
        # so the developer's real vendor registry is neither read nor written.
        env["CRYO_HOME"] = tmp
        env["CRYO_STDLIB"] = STDLIB
        if os.name == "nt":
            env.setdefault("CRYO_CC", "gcc")

        reg = subprocess.run([cryo, "vendor", FIXTURE], env=env,
                             capture_output=True, text=True)
        out = (reg.stdout or "") + (reg.stderr or "")
        if reg.returncode != 0:
            die("`cryo vendor` failed on the fixture", out)

        # A serializer that drops a constant the importer bound must say so.
        dropped = [ln for ln in out.splitlines() if "[skip]" in ln and "const" in ln]
        if dropped:
            die("the serializer reported dropping bound constants",
                "\n".join(dropped))

        m = re.search(r"^\s*bindings:\s*(.+)$", out, re.M)
        if not m:
            die("could not find the generated bindings path in the output", out)
        generated = m.group(1).strip()
        if not os.path.exists(generated):
            die("generated bindings file does not exist: %s" % generated, out)
        with open(generated) as f:
            body = f.read()
        missing = [t for t in GENERATED_MUST_CONTAIN if t not in body]
        if missing:
            die("the generated binding is missing non-const declarations",
                "\n".join("  %s" % t for t in missing), body)

        proj = os.path.join(tmp, "consumer")
        os.makedirs(os.path.join(proj, "src"))
        with open(os.path.join(proj, "cryoconfig"), "w") as f:
            f.write(CRYOCONFIG)
        with open(os.path.join(proj, "src", "main.cryo"), "w") as f:
            f.write(consumer_source())

        # `cryo build` writes its output relative to the CURRENT directory, so
        # the build runs from inside the project rather than pointing at it.
        run = subprocess.run([cryo, "run"], cwd=proj, env=env,
                             capture_output=True, text=True)
        rout = (run.stdout or "") + (run.stderr or "")
        if run.returncode != 0:
            die("the consumer failed to build or run "
                "(a `cannot find value` here means the constant was dropped "
                "from the generated binding)",
                rout, "--- generated binding ---", body)

        got = {}
        for line in (run.stdout or "").splitlines():
            if "=" in line:
                k, _, v = line.partition("=")
                got[k.strip()] = v.strip()

        expected = dict(INT_CONSTS)
        expected[FLOAT_CONST[0]] = FLOAT_CONST[1]
        expected[STRING_CONST[0]] = STRING_CONST[1]

        bad = []
        for name in sorted(expected):
            if name not in got:
                bad.append("  %-14s MISSING from the consumer's output" % name)
            elif got[name] != expected[name]:
                bad.append("  %-14s expected %s, got %s"
                           % (name, expected[name], got[name]))
        if bad:
            die("constant values do not match the header", "\n".join(bad), rout)

        print("vendor-consts gate: OK - %d constants survived generation"
              % len(expected))
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
